export const UPDATE_THREADS = 'UPDATE_THREADS';
export const UPDATE_THREAD = 'UPDATE_THREAD';
export const UNSHIFT_THREADS = 'UNSHIFT_THREADS';
export const APPEND_REPLY_TO_THREAD = 'APPEND_REPLY_TO_THREAD';